version: "3"

services:
  # demo:
  #   container_name: demo
  #   build: .
  #   restart: always
  #   depends_on:
  #     - mongo
  #   ports:
  #     - 8080:8080
  #   environment:
  #     SPRING_APPLICATION_JSON: '{
  #       "spring.data.mongodb.host": "mongo"
  #     }'
  #   # command: ["java", "-jar", "/app.jar"]

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: root
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    # volumes:
    #   - ./MongoDB:/data/db